### ISSUE TITLE
Fix the oauth google log-in to have proper callback URL

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/savannahbudget.party#6]
Whether that's localhost or savannahbudget.party.

**Comment by roblingle** [comment]
Fixed in e3d36805318ef17c15a6b9c607b1f82f5bd2fa49
Domains in the [Firebase project](https://console.firebase.google.com/u/2/project/savannah-budget-party/authentication/providers) include localhost, budget.opensavannah.org, and the firebaseapp built-in.
