### ISSUE TITLE
Getting new error message when running `yarn run deploy` at the end of process at gh-pages

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/savannahbudget.party#7]
Yesterday, was deploying to GH-pages fine. Possible that the changes to `package.json` somehow messed up the deploy to gh-pages?

Here's the error message I get at the end of the deploy attempt:

`$ gh-pages -d build
/bin/sh: gh-pages: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by carlvlewis** [comment]
Again, this runs fine locally with `yarn run start` and it gets all the way through `yarn run deploy` but fails when attempting to carry out the `gh-pages -d build` script, saying `command not found.`

**Comment by carlvlewis** [comment]
I'm unsure what could have changed between today and yesterday other than:

(a) I changed the repo name

(b) looks like @roblingle you maybe made some fixes to clean up `package.json` to be fully yarn deployed and not npm.

**Comment by carlvlewis** [comment]
or 

(c) This could be due to my updates today in which it appears `package.lock.json` somehow crept in... you'll see my multiple attempts to revert.

**Comment by roblingle** [comment]
`gh-pages: command not found` sounds like packages hadn't been installed. Seemed ok to me.
